apiVersion: v1
kind: ConfigMap
metadata:
  name: balancer-config
  labels:
    {{- include "multi-juicer.balancer.labels" . | nindent 4 }}
data:
  config.json: |
    {{ .Values.config | toPrettyJson | nindent 6 }}
