apiVersion: v1
kind: Service
metadata:
  name: balancer-metrics
  labels:
    {{ include "multi-juicer.balancer.labels" . | nindent 4 }}
    type: metrics
spec:
  type: ClusterIP
  selector:
    {{ include "multi-juicer.balancer.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      name: metrics
