apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: balancer
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "multi-juicer.balancer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: balancer # Name is case sensitive
roleRef:
  kind: Role
  name: balancer
  apiGroup: rbac.authorization.k8s.io
