apiVersion: v1
kind: Service
metadata:
  name: multi-juicer-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: balancer-multi-juicer
    app.kubernetes.io/name: balancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
