on: [push, pull_request]
name: "Tests"
permissions:
  contents: read
jobs:
  cleaner:
    name: Cleaner
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cleaner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "cleaner/go.mod"
          cache-dependency-path: "cleaner/go.sum"
      - name: "Lint"
        run: go vet
      - name: "Test"
        run: go test -cover

  balancer:
    name: Balancer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: balancer
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "balancer/go.mod"
          cache-dependency-path: "balancer/go.sum"
      - name: "Lint"
        run: go vet
      - name: "Test"
        run: go test -cover

  progress-watchdog:
    name: ProgressWatchdog
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: progress-watchdog
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "progress-watchdog/go.mod"
          cache-dependency-path: "progress-watchdog/go.sum"
      - name: "Lint"
        run: go vet
      - name: "Test"
        run: go test -cover

  helm:
    name: Helm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: helm/multi-juicer/
    steps:
      - uses: actions/checkout@v4
      - name: Verify tools
        run: |
          helm version
      - name: Install Helm Unit Test Plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 0.6.2
      - name: Helm-Chart Unit Tests | Operator
        run: helm unittest .
